name: AUTUMN
favicon: null
layout_spectrum: 0.2602596709039062
typography_spectrum: 0.5592756264377385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6220200851093978
  lightness: 0.981131691718474
  saturation: 0.8526740972883999
  rhythmicContrast: 0.7501463177613914
purpose: []
